# Generated by Django 2.2.5 on 2019-09-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ip', models.GenericIPAddressField()),
                ('mask', models.GenericIPAddressField()),
                ('route', models.GenericIPAddressField()),
                ('interface_name', models.CharField(max_length=250)),
            ],
        ),
    ]
