# Generated by Django 2.2.5 on 2019-09-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
