# Generated by Django 2.2.5 on 2019-09-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190920_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='interface_name',
            field=models.CharField(max_length=300),
        ),
    ]
