# Generated by Django 2.2.5 on 2019-09-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190920_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
