# Generated by Django 2.2.5 on 2019-09-30 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20190922_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default='2019-09-30'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mask', models.GenericIPAddressField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('manamentip', models.GenericIPAddressField()),
                ('valns', models.ManyToManyField(blank=True, null=True, to='info.Vlan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
